// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_SqlTblDep_Infrastructure.Data;

namespace Test_SqlTblDep_Infrastructure.Migrations
{
    [DbContext(typeof(BigFootDbContext))]
    [Migration("20200215181412_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_SqlTblDep_Infrastructure.Entities.BigFoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Daddy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EyeColor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FootSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Mom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BigFoot");
                });

            modelBuilder.Entity("Test_SqlTblDep_Infrastructure.Entities.EyeColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EyeColor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a401d4e4-fe28-49ba-ac27-f9c76511c4d6"),
                            Color = "Brown"
                        },
                        new
                        {
                            Id = new Guid("56b7f17c-ede7-4575-9ad6-2176b393a8ab"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("c783ac59-b34b-47e1-afcc-5716dd2777ef"),
                            Color = "Grey"
                        },
                        new
                        {
                            Id = new Guid("dfdfd891-3df5-469c-9f9d-84ab856c23cc"),
                            Color = "Yello"
                        },
                        new
                        {
                            Id = new Guid("ec2cc6fc-5afb-4300-b07b-4af521e02093"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("0f51c023-a503-49c8-8bf5-e123f7831133"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("5b3ca54c-4ae5-4bc5-9d65-0d1197844498"),
                            Color = "Pink"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
