// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_SqlTblDep_Infrastructure.Data;

namespace Test_SqlTblDep_Infrastructure.Migrations
{
    [DbContext(typeof(BigFootDbContext))]
    partial class BigFootDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_SqlTblDep_Infrastructure.Entities.BigFoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Daddy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EyeColor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FootSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Mom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isParent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BigFoot");
                });

            modelBuilder.Entity("Test_SqlTblDep_Infrastructure.Entities.EyeColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EyeColor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aadc7f7-6acd-4c72-a221-f5180bcf3ed5"),
                            Color = "Brown"
                        },
                        new
                        {
                            Id = new Guid("7aeb2e86-9141-48fd-a744-1ace00726d94"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("64bc5be1-b86b-4e63-b97a-fd5e6b87d755"),
                            Color = "Grey"
                        },
                        new
                        {
                            Id = new Guid("7aaea121-6c7c-43b5-9cba-0a5a315ed1f7"),
                            Color = "Yello"
                        },
                        new
                        {
                            Id = new Guid("ebe53431-ebca-4c3e-9f93-3f66fefdbb91"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("98f3302d-d501-4de3-a093-65a92487fc1b"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("4931e4f7-fbb1-41f1-a5ce-384bc55617ca"),
                            Color = "Pink"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
